### ISSUE TITLE
Remove metadata from inside data

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/rdl-website#80]
Only the `intensity` field should be kept. `Lat` and `lon` field should also be removed from GeoJSON format.

![Screen Shot 2020-09-30 at 09 44 34](https://user-images.githubusercontent.com/10201533/94657431-bca96200-0301-11eb-97db-da2478e3aaf3.jpg)

**Comment by stufraser1** [comment]
Proposing to move metadata into 'header' of geojson file, and include lat/lon only in the geometry, not as distinct fields
e.g. for hazard (but replicated for Exp/Loss too)


{"@context": 
 {"description": "http://purl.org/dc/terms/description",
    "export": "RiskDataLibrary Hazard data export"},
"id": 18, 
"model_source": "AIR Worldwide", 
"model_date": "2016-01-01", 
"version": "version 1", 
"purpose": "Quantification of site specific risk of flood, earthquakes, tropical cyclones, storm surge and tsunamis, to support improvement in the resiliency and capacity of South West Indian Ocean island states through the creation of disaster risk financing strategies.", 
"project": "GFDRR South West Indian Ocean Risk Assessment and Financing Initiative (SWIO-RAFI)", 
"license_code": "CC BY-SA 4.0", 
"geographic_area_name": "Madagascar", 
"frequency": 0.1, 
"description": "MDG TC Pluvial Flood 10yr event, depth (mm); Metadata contained in geojson file", 
"hazard_name": "Flood", 
"process_name": "Pluvial Flood", 
"description.1": "Flood water depth", 
"units": "m",
"type":"FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features":[ 
  {"type":"Feature","geometry":{"type":"Point","coordinates":[53,0.4]},"properties": {"intensity": 1.34}},
  {"type":"Feature","geometry":{"type":"Point","coordinates":[53.0,0.1]},"properties":{"intensity": 1.34}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[53.0,0.2]},"properties":{"intensity": 2.0}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[53.0,0.3]},"properties":{"intensity": 6.5}}
]
}

**Comment by MamadioCMCC** [comment]
Proposing to do the same also for the csv download: header with metadata followed by table with footprint data (this is a solution found in most database-dumping services e.g. eurostat, others). @ConnectedSystems

**Comment by MamadioCMCC** [comment]
Should I close this and continue a more complete discussion on metadata?
https://github.com/GFDRR/rdl-data/issues/34

**Comment by ConnectedSystems** [comment]
I will close in favor of GFDRR/rdl-data#34 - but will make a note to refer to the discussion here.
