### ISSUE TITLE
Technical documentation link triggers download

### ISSUE THREAD

**Issue by ldodds** [GFDRR/rdl-website#99]
On [the Schemas page](http://riskdatalibrary.org/schemas) there is a link to the technical documentation.

In [the HTML](https://github.com/GFDRR/rdl-website/blob/master/schemas.html#L73), the link element has a `download` attribute:

```
<a href="http://riskdatalibrary.org/documentation" class="link" download target="_blank">Technical information</a>
```

This triggers the browser (Chrome, Firefox) to download the link rather than open it in the browser. I think that needs to be removed to allow a user to navigate to the documentation.

The link to documentation in the page header works OK.

**Comment by ConnectedSystems** [comment]
Hi @ldodds, thanks for catching this.

Would you be able to tell us which browser you're using? 
I clicked around on Chrome, Firefox and Edge and didn't get the behavior you experienced so I'm curious to know.
